apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: assignment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: assignment
    spec:
      containers:
      - name: assignment
        image: viloo/assignment:v1
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"