apiVersion: v1
kind: Service
metadata:
  name: assignment-service
spec:
  selector:
    app: assignment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer